# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'Thermo Cam BLE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thermo Cam BLE
  pod 'OpenCV2'

  target 'Thermo Cam BLETests' do
    inherit! :search_paths
    # Pods for testing
  end

end
